/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
    // Deletes ALL existing entries
    await knex("inventories").del();
    await knex("inventories").insert([
        {
            id: 1,
            store_id: 1,
            item_name: "Lillies",
            colour: "white",
            category: "primary",
            status: "In Stock",
            quantity: 53,
            images: [
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Lillies/kxji6qgkb9hzefwcxrhn",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Lillies/pninvalmy2knefw09kcc",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Lillies/ipsjwbqkzfg1kxh1rxmu",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Lillies/zvyvzbd4ocql7etgfulk",
            ],
        },
        {
            id: 2,
            store_id: 1,
            item_name: "Roses - Red",
            colour: "red",
            category: "primary",
            status: "Out of Stock",
            quantity: 0,
            images: [
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Roses/red/rrb2bgkmncsmn57mtlvz",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Roses/red/pkoe7japihqc4vegbgob",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Roses/red/tihl0rlddx3mnjp5lozl",
            ],
        },
        {
            id: 3,
            store_id: 1,
            item_name: "Roses - White",
            colour: "white",
            category: "primary",
            status: "In Stock",
            quantity: 10,
            images: [
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Roses/white/mg8m7ulkeyhbitynxs1f",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Roses/white/fs7wraf6oxzzzzgdma7d",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Roses/white/hq8oysezee7c2sisbw3q",
            ],
        },
        {
            id: 4,
            store_id: 1,
            item_name: "Carnations",
            colour: "pink",
            category: "primary",
            status: "In Stock",
            quantity: 20,
            images: [
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Carnations/ccgkxvxjxa53yyfhyvsq",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Carnations/bt4ynwiavebrzmyv7mae",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Carnations/x5tenbs9r7avywllrr8p",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Carnations/exhe8dewqgw8rrzq8bah",
            ],
        },
        {
            id: 5,
            store_id: 1,
            item_name: "Hydrangeas ",
            colour: "purple",
            category: "primary",
            status: "In Stock",
            quantity: 7,
            images: [
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Hydrangeas/zn3flaalctggqtbi1ym9",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Hydrangeas/il6bs4lfhgsi5alz40ai",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Hydrangeas/jxng42zaqoxfumrhbbsp",
            ],
        },
        {
            id: 6,
            store_id: 1,
            item_name: "Lilacs",
            colour: "pink",
            category: "primary",
            status: "In Stock",
            quantity: 10,
            images: [
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/lilacs/nw207yqxpju5fkwp4blk",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/lilacs/nxjz95bsegvshzmrtfcq",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/lilacs/jqyktcbsmnxcgqqlqfxn",
            ],
        },
        {
            id: 7,
            store_id: 1,
            item_name: "Roses - Pink",
            colour: "pink",
            category: "primary",
            status: "In Stock",
            quantity: 8,
            images: [
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Roses/pink/xtzotf1oig3oybyh8ugi",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Roses/pink/zv14lc307cxnzdxtpgg1",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Roses/pink/mkiq0igw0k6upjuw2nxc",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Roses/pink/v5cdwzbmrxtek75pq3ao",
            ],
        },
        {
            id: 8,
            store_id: 1,
            item_name: "Peonies - Pink",
            colour: "pink",
            category: "primary",
            status: "In Stock",
            quantity: 2,
            images: [
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Peonies/ilh0dqstwwu4ksgi5ddx",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Peonies/b8ty4agozxfkxawvrsam",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Peonies/hz9vvqwn27l2yfawrxad",
            ],
        },
        {
            id: 9,
            store_id: 1,
            item_name: "Peonies - White",
            colour: "white",
            category: "primary",
            status: "In Stock",
            quantity: 1,
        },
        {
            id: 10,
            store_id: 1,
            item_name: "Sunflowers",
            colour: "yellow",
            category: "primary",
            status: "In Stock",
            quantity: 2,
            images: [
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Sunflowers/epd3rjxfvuxor879cpzt",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Sunflowers/lghepfl8meo3x7kgyjxf",
            ],
        },

        {
            id: 11,
            store_id: 1,
            item_name: "Eucalyptus",
            colour: "green",
            category: "foliage",
            status: "In Stock",
            quantity: 12,
            images: [
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Eucalyptus/wikivauifnjiykf8ivsx",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Eucalyptus/gfr8zgdl8rkjb6rlq5un",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Eucalyptus/rzqr8y75qbkpmmssrppi",
            ],
        },
        {
            id: 12,
            store_id: 1,
            item_name: "Fern",
            colour: "green",
            category: "foliage",
            status: "In Stock",
            quantity: 10,
            images: [
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Fern/sb5mpg1paysaomakzmlb",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Fern/npkjjbxqz5tamqjblloj",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Fern/t2xrzzir7ixkkegczjyg",
            ],
        },
        {
            id: 13,
            store_id: 1,
            item_name: "Myrtle",
            colour: "green",
            category: "foliage",
            status: "In Stock",
            quantity: 8,
            images: [
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/myrtle/uxu82dxudyxcobqq1dup",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/myrtle/ewsizcbzudisd4i63glb",
                "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/myrtle/o6wsq3rdpbl2jzyf6kq3",
            ],
        },
        {
            id: 14,
            store_id: 1,
            item_name: "Vase",
            colour: "clear",
            category: "container",
            status: "In Stock",
            quantity: 3,
            imag: "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Container/lxfrkyeui2bm9xahfgse",
        },
        {
            id: 15,
            store_id: 1,
            item_name: "Kraft Paper",
            colour: "brow",
            category: "container",
            status: "In Stock",
            quantity: 18,
            image: "https://res.cloudinary.com/dxay0tp2l/image/upload/f_auto,q_auto/v1/build-a-bouq/Container/zrnxdymrda2bb1zuwh4q",
        },
    ]);
};
